name: authentication_ui
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  pinput: ^3.0.1
  fluttertoast: ^8.2.4
  flutter_bloc: ^8.1.3
  iconly: ^1.0.1
  google_fonts: ^6.1.0
  curved_navigation_bar: ^1.0.3
  font_awesome_flutter: ^10.6.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  email_validator: ^2.0.1
  string_validator: ^1.0.2
  flutter_spinkit: ^5.2.0
  loading_animation_widget: ^1.2.0+4
  flutter_riverpod: ^1.0.0
  audioplayers: ^0.18.3
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.12
  file_picker: any
  open_filex: ^4.4.0
  permission_handler: ^8.1.6
  flutter_callkit_incoming: ^2.0.1+2
  firebase_core: ^2.25.4
  flutter_slidable: ^0.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/messages.json
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf
