name: authentication_ui
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  pinput: ^3.0.1
  fluttertoast: ^8.2.4
  flutter_bloc: ^8.1.3
  iconly: ^1.0.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf
